CREATE TABLE Usuarios (
    UID INTEGER PRIMARY KEY AUTOINCREMENT,
    login_name TEXT NOT NULL UNIQUE, -- EMAIL
    GID INTEGER,
    nome TEXT NOT NULL,
    senha TEXT NOT NULL,
    numero_acessos INTEGER DEFAULT 0,
    numero_consultas INTEGER DEFAULT 0,
    FOREIGN KEY (GID) REFERENCES Grupos(GID)
);

CREATE TABLE Chaveiro (
    KID INTEGER PRIMARY KEY AUTOINCREMENT,
    UID INTEGER NOT NULL,
    certificado_digital BLOB NOT NULL,
    chave_privada BLOB NOT NULL,
    FOREIGN KEY (UID) REFERENCES Usuarios (UID)
);

CREATE TABLE Grupos (
    GID INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL
);


CREATE TABLE Mensagens (
    MID INTEGER PRIMARY KEY AUTOINCREMENT,
    conteudo TEXT NOT NULL
);


CREATE TABLE Registros (
    RID INTEGER PRIMARY KEY AUTOINCREMENT,
    UID INTEGER,
    MID INTEGER NOT NULL,
    data_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    descricao TEXT,
    FOREIGN KEY (UID) REFERENCES Usuarios (UID),
    FOREIGN KEY (MID) REFERENCES Mensagens (MID)
);